//! Conform a primitive's mesh onto a path along a target surface.
//!
//! The kernel takes a child mesh in some local frame, plus a sequence of
//! `PathFrame`s describing where the path goes on the target surface (in
//! the same coordinate space as the child positions you pass in), and
//! returns a deformed mesh whose vertices have been remapped onto that
//! surface path.
//!
//! ## Coordinate spaces
//!
//! The kernel does not deal in world matrices. Callers are expected to
//! either (a) pre-transform the child mesh into target-local space before
//! calling and post-transform the result back, or (b) supply the path
//! frames in whatever space the child positions live in. This keeps the
//! kernel free of glTF-vs-graph wiring concerns.
//!
//! ## Axes
//!
//! [`AxisMap`] picks which child-local axis is the path axis (`along`),
//! which lies tangent to the surface perpendicular to the path (`width`),
//! and which is "thickness" (`height`, the surface-outward axis). The
//! deformation is then:
//!
//! ```text
//! v_new = center(t) + binormal(t) * w + normal(t) * (h + lift)
//! ```
//!
//! where `t` is the child vertex's normalized position along the `along`
//! axis, mapped through the path samples.
//!
//! ## Frame propagation
//!
//! `build_path_frames` lays a chord between the two endpoint surface
//! points, projects each chord sample back onto the surface (the
//! "chord-and-snap" strategy from the design doc), then computes a
//! tangent / surface-normal / binormal triple at each sample. Twist —
//! when set — is applied as a rotation around the tangent that ramps
//! linearly from `0` at sample `0` to `twist_deg` at the last sample.

use glam::{Quat, Vec3};

use mogen_core::Mesh;

use crate::surface_query::SurfaceIndex;

/// One of the three child-local cardinal axes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Axis {
    X,
    Y,
    Z,
}

impl Axis {
    pub fn index(self) -> usize {
        match self {
            Axis::X => 0,
            Axis::Y => 1,
            Axis::Z => 2,
        }
    }
}

/// Maps the child's local axes to the conform path's three roles:
///
/// - `along` — the path axis. Vertex coordinate on this axis maps
///   monotonically into path parameter `t ∈ [0, 1]`.
/// - `width` — perpendicular to the path, tangent to the target surface.
///   Vertex coordinate on this axis is preserved as a metric offset.
/// - `height` — the "thickness" axis. Vertex coordinate is preserved as a
///   metric offset along the surface normal (plus the global `lift`).
///
/// The three axes must be distinct.
#[derive(Debug, Clone, Copy)]
pub struct AxisMap {
    pub along: Axis,
    pub width: Axis,
    pub height: Axis,
}

impl AxisMap {
    pub fn is_valid(self) -> bool {
        self.along != self.width && self.along != self.height && self.width != self.height
    }

    /// A sensible default given just the `along` axis: `width` and
    /// `height` are picked from the remaining two axes such that the
    /// triple forms a right-handed frame analogous to (X=along, Y=height,
    /// Z=width).
    pub fn from_along(along: Axis) -> Self {
        let (width, height) = match along {
            Axis::X => (Axis::Z, Axis::Y),
            Axis::Y => (Axis::X, Axis::Z),
            Axis::Z => (Axis::X, Axis::Y),
        };
        Self { along, width, height }
    }
}

/// Per-sample frame along the conform path. All vectors are unit length
/// and mutually perpendicular: `tangent × normal = binormal`.
#[derive(Debug, Clone, Copy)]
pub struct PathFrame {
    pub center: Vec3,
    pub tangent: Vec3,
    pub normal: Vec3,
    pub binormal: Vec3,
}

/// Static parameters for [`conform_mesh`].
#[derive(Debug, Clone, Copy)]
pub struct ConformParams {
    pub axes: AxisMap,
    pub lift: f32,
}

/// Build a sequence of frames along the path from `s_a` to `s_b` on the
/// target `surface`. `samples` is the number of samples to generate
/// (clamped to `>= 2`). `twist_deg` is the total roll applied around the
/// path tangent, ramped linearly from `0` to `twist_deg` across the path.
///
/// The path is generated by the chord-and-snap strategy: for each sample
/// `t ∈ [0, 1]`, take the linear interpolation `lerp(s_a, s_b, t)` and
/// project it onto the surface via `SurfaceIndex::closest_point`. This
/// approximates a geodesic well enough for the typical conform scenarios
/// where the surface curves smoothly between the endpoints; for highly
/// twisted topologies, increase `samples`.
///
/// Returns an empty vec if `surface.is_empty()`.
pub fn build_path_frames(
    surface: &SurfaceIndex,
    s_a: Vec3,
    s_b: Vec3,
    samples: u32,
    twist_deg: f32,
) -> Vec<PathFrame> {
    if surface.is_empty() {
        return Vec::new();
    }
    let n = (samples as usize).max(2);

    let mut centers: Vec<Vec3> = Vec::with_capacity(n);
    let mut surf_normals: Vec<Vec3> = Vec::with_capacity(n);
    for i in 0..n {
        let t = i as f32 / (n - 1) as f32;
        let chord = s_a.lerp(s_b, t);
        let sp = match surface.closest_point(chord) {
            Some(sp) => sp,
            None => return Vec::new(),
        };
        centers.push(sp.pos);
        surf_normals.push(sp.normal);
    }

    let mut frames = Vec::with_capacity(n);
    for i in 0..n {
        // Symmetric difference for tangent; one-sided at the endpoints.
        let tangent = if i == 0 {
            (centers[1] - centers[0]).normalize_or_zero()
        } else if i == n - 1 {
            (centers[n - 1] - centers[n - 2]).normalize_or_zero()
        } else {
            (centers[i + 1] - centers[i - 1]).normalize_or_zero()
        };

        // Project the surface normal onto the plane perpendicular to the
        // tangent so the resulting frame is exactly orthonormal. If the
        // surface normal happens to be parallel to the tangent (degenerate),
        // fall back to any vector perpendicular to the tangent.
        let raw_normal = surf_normals[i].normalize_or_zero();
        let perp = raw_normal - tangent * tangent.dot(raw_normal);
        let mut normal = perp.normalize_or_zero();
        if normal == Vec3::ZERO {
            // Pick an arbitrary perpendicular (`tangent` is non-zero by the
            // surface-snap above).
            let helper = if tangent.y.abs() < 0.9 { Vec3::Y } else { Vec3::X };
            normal = (helper - tangent * tangent.dot(helper)).normalize_or_zero();
        }
        let mut binormal = tangent.cross(normal).normalize_or_zero();
        // Re-orthogonalize normal against the (now well-defined) binormal
        // to guarantee orthonormality after numerical drift.
        normal = binormal.cross(tangent).normalize_or_zero();

        // Ramp twist linearly across the path. `twist_deg` of 0 is a no-op.
        if twist_deg != 0.0 {
            let t = i as f32 / (n - 1) as f32;
            let q = Quat::from_axis_angle(tangent, (twist_deg * t).to_radians());
            normal = (q * normal).normalize_or_zero();
            binormal = (q * binormal).normalize_or_zero();
        }

        frames.push(PathFrame { center: centers[i], tangent, normal, binormal });
    }

    frames
}

/// Deform `child` so its vertices follow `path_frames`. See module docs
/// for coordinate-space conventions and the deformation formula.
///
/// Returns a new mesh: positions are remapped, normals are re-derived
/// from the deformed geometry by averaging adjacent face normals, and
/// every other field (UVs, joints, weights, indices) is preserved
/// unchanged. If `path_frames.len() < 2` or `child.positions.is_empty()`
/// or [`AxisMap::is_valid`] is false, the input mesh is returned cloned
/// untouched — callers are expected to validate at higher levels.
pub fn conform_mesh(child: &Mesh, path_frames: &[PathFrame], params: &ConformParams) -> Mesh {
    if path_frames.len() < 2 || child.positions.is_empty() || !params.axes.is_valid() {
        return child.clone();
    }

    let along_idx = params.axes.along.index();
    let width_idx = params.axes.width.index();
    let height_idx = params.axes.height.index();

    let mut along_min = f32::INFINITY;
    let mut along_max = f32::NEG_INFINITY;
    for p in &child.positions {
        let v = p[along_idx];
        if v < along_min {
            along_min = v;
        }
        if v > along_max {
            along_max = v;
        }
    }
    let along_span = (along_max - along_min).max(1e-6);

    let n = path_frames.len();
    let last = (n - 1) as f32;

    let mut out = child.clone();
    for (i, p) in child.positions.iter().enumerate() {
        let t = (p[along_idx] - along_min) / along_span;
        let s = (t * last).clamp(0.0, last);
        let lo = (s as usize).min(n - 2);
        let f = s - lo as f32;

        let a = &path_frames[lo];
        let b = &path_frames[lo + 1];
        let center = a.center.lerp(b.center, f);
        // Slerp-style interpolation for orthogonal axes is overkill; lerp
        // and re-orthonormalize. The samples are dense enough that adjacent
        // frames are nearly identical, so lerp is visually indistinguishable
        // from slerp.
        let tangent = a.tangent.lerp(b.tangent, f).normalize_or_zero();
        let mut normal = a.normal.lerp(b.normal, f).normalize_or_zero();
        let mut binormal = tangent.cross(normal).normalize_or_zero();
        normal = binormal.cross(tangent).normalize_or_zero();
        // Preserve the binormal sign relative to the input frame so the
        // strip doesn't flip-flop near sharp curvature.
        let avg_bin = a.binormal.lerp(b.binormal, f);
        if binormal.dot(avg_bin) < 0.0 {
            binormal = -binormal;
            normal = -normal;
        }

        let w = p[width_idx];
        let h = p[height_idx];
        let new_pos = center + binormal * w + normal * (h + params.lift);
        out.positions[i] = new_pos.to_array();
    }

    // Re-derive normals from the deformed geometry. Done in-place so
    // skinning data (joints/weights) and UVs survive — `cleanup::
    // recompute_normals` would rebuild a fresh mesh and drop them.
    if !out.normals.is_empty() && !out.indices.is_empty() {
        let mut acc = vec![Vec3::ZERO; out.positions.len()];
        for tri in out.indices.chunks_exact(3) {
            let ia = tri[0] as usize;
            let ib = tri[1] as usize;
            let ic = tri[2] as usize;
            let pa = Vec3::from_array(out.positions[ia]);
            let pb = Vec3::from_array(out.positions[ib]);
            let pc = Vec3::from_array(out.positions[ic]);
            let face_n = (pb - pa).cross(pc - pa);
            acc[ia] += face_n;
            acc[ib] += face_n;
            acc[ic] += face_n;
        }
        for (i, n) in acc.iter().enumerate() {
            let v = n.normalize_or_zero();
            out.normals[i] = [v.x, v.y, v.z];
        }
    }

    out
}

/// Static parameters for [`conform_patch`].
///
/// Where [`ConformParams`] describes a strip stretched between two endpoints,
/// `PatchParams` describes a flat / disc-shaped child laid down at a single
/// anchor on the surface. The child's `up` axis is collapsed onto the surface
/// outward normal at every vertex; the other two axes parameterize a plane
/// tangent to the surface.
#[derive(Debug, Clone, Copy)]
pub struct PatchParams {
    /// Child-local axis that maps to the surface's outward normal direction.
    /// For a `disc` (XZ plane facing +Y), this is `Axis::Y`; for a `quad`
    /// (XY plane facing +Z), it's `Axis::Z`.
    pub up: Axis,
    /// Where to place the patch centre in target-local space. Snapped to the
    /// surface inside the kernel.
    pub anchor: Vec3,
    /// Optional outward direction at the anchor. When `None` the kernel uses
    /// the surface normal at the snapped anchor point. When `Some`, this is
    /// projected onto the surface-tangent plane to compute the in-plane frame
    /// — useful when the user wants the patch to face a specific direction
    /// (e.g. a connector's `dir`).
    pub anchor_dir: Option<Vec3>,
    /// Optional in-plane reference vector that locks the patch's roll around
    /// the normal. The kernel projects it onto the tangent plane to derive
    /// the first tangent axis. When `None`, a stable arbitrary tangent is
    /// chosen (world-Y, falling back to world-X if too parallel to N).
    pub roll_ref: Option<Vec3>,
    /// Constant outward offset along the surface normal, in addition to the
    /// vertex's own up-axis coordinate.
    pub lift: f32,
}

/// Lay `child` down as a patch at `params.anchor` on `surface`. Each child
/// vertex is decomposed into `(s1, s2, h)` along the patch's local frame
/// (`s1`, `s2` in the surface-tangent plane, `h` along the surface normal),
/// the planar position is independently snapped to the surface, and the
/// height is added back along the local normal at that snap. This makes a
/// flat disc bend to follow the surface's curvature without forcing the
/// caller to pick an "along" axis or supply two endpoints.
///
/// Returns the input cloned untouched when `surface.is_empty()` or
/// `child.positions.is_empty()`.
pub fn conform_patch(child: &Mesh, surface: &SurfaceIndex, params: &PatchParams) -> Mesh {
    if surface.is_empty() || child.positions.is_empty() {
        return child.clone();
    }

    let sp0 = match surface.closest_point(params.anchor) {
        Some(sp) => sp,
        None => return child.clone(),
    };

    // Outward normal at the anchor — explicit override takes precedence,
    // otherwise the surface normal. We always re-snap each vertex below, so
    // `n0` only sets the orienting frame's roll basis, not the per-vertex
    // height direction.
    let n0 = params
        .anchor_dir
        .map(|d| d.normalize_or_zero())
        .filter(|d| *d != Vec3::ZERO)
        .unwrap_or_else(|| sp0.normal.normalize_or_zero());
    let n0 = if n0 == Vec3::ZERO { Vec3::Y } else { n0 };

    // First tangent: project `roll_ref` onto plane⊥n0, falling back to a
    // stable arbitrary perpendicular when not supplied (or near-parallel).
    let t0 = {
        let helper = params
            .roll_ref
            .filter(|v| *v != Vec3::ZERO)
            .unwrap_or(if n0.y.abs() < 0.9 { Vec3::Y } else { Vec3::X });
        let projected = helper - n0 * n0.dot(helper);
        let mut t = projected.normalize_or_zero();
        if t == Vec3::ZERO {
            let fallback = if n0.x.abs() < 0.9 { Vec3::X } else { Vec3::Z };
            t = (fallback - n0 * n0.dot(fallback)).normalize_or_zero();
        }
        t
    };
    let b0 = n0.cross(t0).normalize_or_zero();

    let up_idx = params.up.index();
    // Pick the two non-up axes for the in-plane decomposition. The convention
    // is: the "first" tangent (T) carries the lower-numbered remaining axis,
    // the "second" tangent (B) carries the higher-numbered. For up=Y this is
    // (T←X, B←Z), matching the disc's natural orientation.
    let (t_idx, b_idx) = match params.up {
        Axis::X => (1usize, 2usize), // up=X → T←Y, B←Z
        Axis::Y => (0usize, 2usize), // up=Y → T←X, B←Z
        Axis::Z => (0usize, 1usize), // up=Z → T←X, B←Y
    };

    let mut out = child.clone();
    for (i, p) in child.positions.iter().enumerate() {
        let s1 = p[t_idx];
        let s2 = p[b_idx];
        let h = p[up_idx];

        let plane_pos = sp0.pos + t0 * s1 + b0 * s2;
        let sp = surface.closest_point(plane_pos).unwrap_or(sp0);
        let normal = {
            let n = sp.normal.normalize_or_zero();
            if n == Vec3::ZERO { n0 } else { n }
        };
        let new_pos = sp.pos + normal * (h + params.lift);
        out.positions[i] = new_pos.to_array();
    }

    // Re-derive normals from the deformed geometry so shading reflects the
    // new curvature. Mirrors conform_mesh's in-place treatment to preserve
    // UVs, joints, and weights.
    if !out.normals.is_empty() && !out.indices.is_empty() {
        let mut acc = vec![Vec3::ZERO; out.positions.len()];
        for tri in out.indices.chunks_exact(3) {
            let ia = tri[0] as usize;
            let ib = tri[1] as usize;
            let ic = tri[2] as usize;
            let pa = Vec3::from_array(out.positions[ia]);
            let pb = Vec3::from_array(out.positions[ib]);
            let pc = Vec3::from_array(out.positions[ic]);
            let face_n = (pb - pa).cross(pc - pa);
            acc[ia] += face_n;
            acc[ib] += face_n;
            acc[ic] += face_n;
        }
        for (i, n) in acc.iter().enumerate() {
            let v = n.normalize_or_zero();
            out.normals[i] = [v.x, v.y, v.z];
        }
    }

    out
}

/// Insert evenly-spaced planar cuts perpendicular to `axis` so the mesh
/// has at least `target_segments + 1` distinct positions along that axis.
///
/// Conform's deformation maps each child vertex's coordinate along the
/// path axis to a sample of the path frames. With a coarse axis (e.g. a
/// raw `box` only has 2 distinct values along each axis), all interior
/// path frames are skipped and the strip stays straight. This routine
/// adds the missing subdivisions so the deformation can follow the
/// path's curvature.
///
/// Triangle meshes only. Returns an unchanged clone if the mesh already
/// has enough distinct positions, or if `target_segments < 2`. UVs and
/// normals are linearly interpolated at new vertices; for skinned meshes
/// the dominant-side joint set is copied (no joint blending).
pub fn subdivide_along_axis(mesh: &Mesh, axis: Axis, target_segments: u32) -> Mesh {
    if mesh.positions.is_empty() || mesh.indices.is_empty() || target_segments < 2 {
        return mesh.clone();
    }
    let axis_idx = axis.index();

    let mut vals: Vec<f32> = mesh.positions.iter().map(|p| p[axis_idx]).collect();
    vals.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let mut distinct: u32 = 1;
    for w in vals.windows(2) {
        if (w[1] - w[0]).abs() > 1e-5 {
            distinct += 1;
        }
    }
    if distinct >= target_segments + 1 {
        return mesh.clone();
    }

    let a_min = *vals.first().unwrap();
    let a_max = *vals.last().unwrap();
    let span = a_max - a_min;
    if span < 1e-6 {
        return mesh.clone();
    }

    let mut current = mesh.clone();
    for i in 1..target_segments {
        let t = i as f32 / target_segments as f32;
        let plane = a_min + span * t;
        current = cut_mesh_at_plane(&current, axis_idx, plane);
    }
    current
}

fn cut_mesh_at_plane(mesh: &Mesh, axis_idx: usize, plane: f32) -> Mesh {
    const EPS: f32 = 1e-6;
    let mut positions = mesh.positions.clone();
    let mut normals = mesh.normals.clone();
    let mut uvs = mesh.uvs.clone();
    let mut joints = mesh.joints.clone();
    let mut weights = mesh.weights.clone();
    let mut indices: Vec<u32> = Vec::with_capacity(mesh.indices.len());
    let has_normals = !mesh.normals.is_empty();
    let has_uvs = !mesh.uvs.is_empty();
    let has_skin = !mesh.joints.is_empty();

    for tri in mesh.indices.chunks_exact(3) {
        let v = [tri[0] as usize, tri[1] as usize, tri[2] as usize];
        let d = [
            positions[v[0]][axis_idx] - plane,
            positions[v[1]][axis_idx] - plane,
            positions[v[2]][axis_idx] - plane,
        ];
        let signs: [i32; 3] = [
            sign_of(d[0], EPS),
            sign_of(d[1], EPS),
            sign_of(d[2], EPS),
        ];
        let pos_count = signs.iter().filter(|&&s| s > 0).count();
        let neg_count = signs.iter().filter(|&&s| s < 0).count();

        if pos_count == 0 || neg_count == 0 {
            indices.extend_from_slice(tri);
            continue;
        }

        // One vertex on plane, one above, one below: split along the single
        // crossing edge into two sub-tris.
        if pos_count == 1 && neg_count == 1 {
            let zero_i = signs.iter().position(|&s| s == 0).unwrap();
            let pos_i = signs.iter().position(|&s| s > 0).unwrap();
            let neg_i = signs.iter().position(|&s| s < 0).unwrap();
            let t = d[pos_i] / (d[pos_i] - d[neg_i]);
            let new_v = interp_vertex(
                v[pos_i], v[neg_i], t,
                &mut positions, &mut normals, &mut uvs,
                &mut joints, &mut weights,
                has_normals, has_uvs, has_skin,
            );
            // Walk the original cycle from `zero_i` so the sub-tri winding
            // matches the parent triangle.
            let next = (zero_i + 1) % 3;
            let nnext = (zero_i + 2) % 3;
            let (mid, far) = if next == pos_i {
                (new_v, tri[neg_i])
            } else {
                (new_v, tri[pos_i])
            };
            indices.extend_from_slice(&[tri[zero_i], tri[next], mid]);
            indices.extend_from_slice(&[tri[zero_i], mid, far]);
            let _ = nnext;
            continue;
        }

        // 1-vs-2 split: one vertex on one side, two on the other. Two edges
        // cross the plane.
        let lone_i = if pos_count == 1 {
            signs.iter().position(|&s| s > 0).unwrap()
        } else {
            signs.iter().position(|&s| s < 0).unwrap()
        };
        let pair_a_i = (lone_i + 1) % 3;
        let pair_b_i = (lone_i + 2) % 3;

        let t_a = d[lone_i] / (d[lone_i] - d[pair_a_i]);
        let t_b = d[lone_i] / (d[lone_i] - d[pair_b_i]);

        let new_a = interp_vertex(
            v[lone_i], v[pair_a_i], t_a,
            &mut positions, &mut normals, &mut uvs,
            &mut joints, &mut weights,
            has_normals, has_uvs, has_skin,
        );
        let new_b = interp_vertex(
            v[lone_i], v[pair_b_i], t_b,
            &mut positions, &mut normals, &mut uvs,
            &mut joints, &mut weights,
            has_normals, has_uvs, has_skin,
        );

        indices.extend_from_slice(&[tri[lone_i], new_a, new_b]);
        indices.extend_from_slice(&[new_a, tri[pair_a_i], tri[pair_b_i]]);
        indices.extend_from_slice(&[new_a, tri[pair_b_i], new_b]);
    }

    Mesh { positions, normals, uvs, indices, joints, weights, colors: Vec::new() }
}

fn sign_of(d: f32, eps: f32) -> i32 {
    if d > eps {
        1
    } else if d < -eps {
        -1
    } else {
        0
    }
}

#[allow(clippy::too_many_arguments)]
fn interp_vertex(
    a: usize, b: usize, t: f32,
    positions: &mut Vec<[f32; 3]>,
    normals: &mut Vec<[f32; 3]>,
    uvs: &mut Vec<[f32; 2]>,
    joints: &mut Vec<[u16; 4]>,
    weights: &mut Vec<[f32; 4]>,
    has_normals: bool,
    has_uvs: bool,
    has_skin: bool,
) -> u32 {
    let pa = positions[a];
    let pb = positions[b];
    positions.push([
        pa[0] + (pb[0] - pa[0]) * t,
        pa[1] + (pb[1] - pa[1]) * t,
        pa[2] + (pb[2] - pa[2]) * t,
    ]);
    if has_normals {
        let na = normals[a];
        let nb = normals[b];
        let n = [
            na[0] + (nb[0] - na[0]) * t,
            na[1] + (nb[1] - na[1]) * t,
            na[2] + (nb[2] - na[2]) * t,
        ];
        let l = (n[0] * n[0] + n[1] * n[1] + n[2] * n[2]).sqrt().max(1e-8);
        normals.push([n[0] / l, n[1] / l, n[2] / l]);
    }
    if has_uvs {
        let ua = uvs[a];
        let ub = uvs[b];
        uvs.push([ua[0] + (ub[0] - ua[0]) * t, ua[1] + (ub[1] - ua[1]) * t]);
    }
    if has_skin {
        let src = if t < 0.5 { a } else { b };
        joints.push(joints[src]);
        weights.push(weights[src]);
    }
    (positions.len() - 1) as u32
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::primitives::{plane_mesh, sphere_mesh};
    use crate::surface_query::SurfaceIndex;
    use mogen_core::UvMode;

    fn flat_strip(len_x: f32, width_z: f32, height_y: f32) -> Mesh {
        // A simple unit box centered at origin with the given dimensions.
        crate::primitives::box_mesh([len_x, height_y, width_z], UvMode::default())
    }

    #[test]
    fn flat_target_is_near_identity_modulo_rigid_transform() {
        // Conform a flat strip onto a flat plane: the deformed mesh should
        // look like the original strip just rigidly placed onto the plane,
        // not warped.
        let plane = plane_mesh([4.0, 4.0], UvMode::default());
        let surface = SurfaceIndex::build(&plane);

        let strip = flat_strip(2.0, 0.2, 0.04);

        // Place the path along +X at the plane (y=0). The chord runs from
        // (-1, 0, 0) to (1, 0, 0); both endpoints already lie on the plane.
        let frames = build_path_frames(&surface, Vec3::new(-1.0, 0.0, 0.0), Vec3::new(1.0, 0.0, 0.0), 32, 0.0);
        assert_eq!(frames.len(), 32);

        let params = ConformParams {
            axes: AxisMap::from_along(Axis::X),
            lift: 0.0,
        };
        let out = conform_mesh(&strip, &frames, &params);

        assert_eq!(out.positions.len(), strip.positions.len());
        // Every output vertex's distance to the plane (|y| since plane lies
        // at y=0) should equal its original |y| ± numerical noise — i.e.,
        // the height-axis offsets are preserved.
        for (orig, new) in strip.positions.iter().zip(out.positions.iter()) {
            let dy_orig = orig[1].abs();
            let dy_new = new[1].abs();
            assert!(
                (dy_orig - dy_new).abs() < 1e-3,
                "vertex y mismatch: orig={dy_orig}, new={dy_new}",
            );
        }
    }

    #[test]
    fn conform_to_sphere_lifts_along_radial_normal() {
        // A flat strip conformed onto the equator of a sphere should have
        // every vertex sit at radius (1.0 + lift) from the sphere's centre,
        // give or take the strip's own thickness in the height axis.
        let sphere = sphere_mesh(1.0, 16, 24, UvMode::default());
        let surface = SurfaceIndex::build(&sphere);

        // Strip 1m long, 2cm wide, 1mm thick. Path runs across the equator
        // (y=0) from -X to +X.
        let strip = crate::primitives::box_mesh([1.0, 0.001, 0.02], UvMode::default());
        let frames = build_path_frames(
            &surface,
            Vec3::new(-1.0, 0.0, 0.0),
            Vec3::new(1.0, 0.0, 0.0),
            64,
            0.0,
        );

        let params = ConformParams {
            axes: AxisMap::from_along(Axis::X),
            lift: 0.005,
        };
        let out = conform_mesh(&strip, &frames, &params);

        // Sphere radius 1, lift 5mm, strip half-thickness ≤ 0.5mm. So every
        // vertex sits at distance 1.0050 ± ~0.001 from the origin.
        for p in &out.positions {
            let r = Vec3::from_array(*p).length();
            assert!(
                (r - 1.005).abs() < 0.01,
                "vertex radius {r} far from expected ~1.005",
            );
        }
    }

    #[test]
    fn empty_path_returns_input_unchanged() {
        let strip = flat_strip(1.0, 0.1, 0.02);
        let params = ConformParams { axes: AxisMap::from_along(Axis::X), lift: 0.0 };
        let out = conform_mesh(&strip, &[], &params);
        assert_eq!(out.positions, strip.positions);
    }

    #[test]
    fn axis_map_validity_rejects_duplicates() {
        let bad = AxisMap { along: Axis::X, width: Axis::X, height: Axis::Y };
        assert!(!bad.is_valid());
        let good = AxisMap::from_along(Axis::X);
        assert!(good.is_valid());
    }

    #[test]
    fn subdivide_box_increases_distinct_along_axis() {
        let strip = crate::primitives::box_mesh([1.0, 0.01, 0.05], UvMode::default());
        // Bare box has only two distinct X positions (the two end faces).
        let xs0: std::collections::BTreeSet<i64> =
            strip.positions.iter().map(|p| (p[0] * 1e4) as i64).collect();
        assert_eq!(xs0.len(), 2);

        let dense = subdivide_along_axis(&strip, Axis::X, 16);
        let xs1: std::collections::BTreeSet<i64> =
            dense.positions.iter().map(|p| (p[0] * 1e4) as i64).collect();
        assert!(
            xs1.len() >= 17,
            "expected at least 17 distinct x values after subdivide, got {}",
            xs1.len()
        );

        // Indices remain a multiple of 3 (still a triangle list).
        assert_eq!(dense.indices.len() % 3, 0);
        // Every index references a real vertex.
        for &i in &dense.indices {
            assert!((i as usize) < dense.positions.len());
        }
    }

    #[test]
    fn subdivide_preserves_extent_and_volume() {
        let strip = crate::primitives::box_mesh([2.0, 0.1, 0.4], UvMode::default());
        let dense = subdivide_along_axis(&strip, Axis::X, 8);
        // AABB unchanged.
        let aabb = |m: &Mesh, axis: usize| -> (f32, f32) {
            let mut lo = f32::INFINITY;
            let mut hi = f32::NEG_INFINITY;
            for p in &m.positions {
                lo = lo.min(p[axis]);
                hi = hi.max(p[axis]);
            }
            (lo, hi)
        };
        for axis in 0..3 {
            let a = aabb(&strip, axis);
            let b = aabb(&dense, axis);
            assert!((a.0 - b.0).abs() < 1e-5 && (a.1 - b.1).abs() < 1e-5);
        }
    }

    #[test]
    fn subdivide_no_op_when_already_dense() {
        // A curved_plane with segments_u=24 already has 25 distinct X positions.
        let m = crate::primitives::curved_plane_mesh([1.0, 0.1], 0.0, 0.0, 24, 1, UvMode::default());
        let n = subdivide_along_axis(&m, Axis::X, 16);
        assert_eq!(m.positions.len(), n.positions.len());
        assert_eq!(m.indices.len(), n.indices.len());
    }

    #[test]
    fn subdivide_then_conform_follows_curved_path() {
        // Without subdivision, a 2-vertex-along box maps every vertex to the
        // path endpoints — the strip stays straight. Subdividing first lets
        // the deformation track the sphere's curvature.
        //
        // The chord is offset from the sphere centre so closest-point queries
        // stay well-defined along the path (a chord through the centre is
        // ambiguous and not the case auto-subdivision is meant to address).
        let sphere = sphere_mesh(1.0, 16, 24, UvMode::default());
        let surface = SurfaceIndex::build(&sphere);
        let strip = crate::primitives::box_mesh([1.5, 0.001, 0.02], UvMode::default());
        let dense = subdivide_along_axis(&strip, Axis::X, 24);

        let frames = build_path_frames(
            &surface,
            Vec3::new(-0.9, 0.0, 0.5),
            Vec3::new(0.9, 0.0, 0.5),
            64,
            0.0,
        );
        let params = ConformParams {
            axes: AxisMap::from_along(Axis::X),
            lift: 0.0,
        };
        let out_dense = conform_mesh(&dense, &frames, &params);
        let out_bare = conform_mesh(&strip, &frames, &params);

        // Both outputs sit on the sphere; the dense one has interior
        // vertices that lift toward +Z as the path arcs over the surface.
        let mid_z_bare: f32 = out_bare
            .positions
            .iter()
            .filter(|p| p[0].abs() < 0.4)
            .map(|p| p[2])
            .sum::<f32>()
            / out_bare.positions.iter().filter(|p| p[0].abs() < 0.4).count().max(1) as f32;
        let mid_z_dense: f32 = out_dense
            .positions
            .iter()
            .filter(|p| p[0].abs() < 0.4)
            .map(|p| p[2])
            .sum::<f32>()
            / out_dense.positions.iter().filter(|p| p[0].abs() < 0.4).count().max(1) as f32;

        // Bare box: no interior vertices, average z near 0 (or undefined).
        // Dense: mid-x vertices should lift along the path (z near +1).
        assert!(
            mid_z_dense > 0.7,
            "dense mid-z {mid_z_dense} should be near sphere top (~1.0); bare={mid_z_bare}"
        );
    }

    #[test]
    fn patch_disc_on_flat_plane_is_translation_only() {
        // A disc laid down on a flat plane should preserve its shape
        // exactly: every rim vertex stays at radius `r` from the anchor,
        // y stays at lift.
        let plane = plane_mesh([4.0, 4.0], UvMode::default());
        let surface = SurfaceIndex::build(&plane);
        let disc = crate::primitives::disc_mesh(0.3, 24, UvMode::default());
        let params = PatchParams {
            up: Axis::Y,
            anchor: Vec3::new(0.5, 0.0, -0.2),
            anchor_dir: None,
            roll_ref: None,
            lift: 0.001,
        };
        let out = conform_patch(&disc, &surface, &params);
        assert_eq!(out.positions.len(), disc.positions.len());

        for (orig, new) in disc.positions.iter().zip(out.positions.iter()) {
            // y is the up-axis on the plane (plane faces +Y) so vertices
            // sit at y = 0 + lift.
            assert!(
                (new[1] - 0.001).abs() < 1e-3,
                "patch vertex y {} not at lift {}",
                new[1],
                0.001
            );
            // Planar distance from anchor matches the original disc's
            // distance from its centre.
            let dx_o = orig[0] - 0.0;
            let dz_o = orig[2] - 0.0;
            let dx_n = new[0] - 0.5;
            let dz_n = new[2] - (-0.2);
            let r_o = (dx_o * dx_o + dz_o * dz_o).sqrt();
            let r_n = (dx_n * dx_n + dz_n * dz_n).sqrt();
            assert!(
                (r_o - r_n).abs() < 1e-3,
                "rim radius drifted: orig={r_o}, new={r_n}",
            );
        }
    }

    #[test]
    fn patch_disc_on_sphere_wraps_to_surface() {
        // Lay a small disc onto a sphere: every vertex should sit at
        // approximately (sphere_radius + lift) from the sphere centre,
        // because conform_patch independently snaps each vertex to the
        // sphere surface.
        let sphere = sphere_mesh(1.0, 32, 48, UvMode::default());
        let surface = SurfaceIndex::build(&sphere);
        let disc = crate::primitives::disc_mesh(0.15, 32, UvMode::default());
        let lift = 0.01;
        let params = PatchParams {
            up: Axis::Y,
            anchor: Vec3::new(0.0, 1.0, 0.0), // top of sphere
            anchor_dir: None,
            roll_ref: None,
            lift,
        };
        let out = conform_patch(&disc, &surface, &params);

        for p in &out.positions {
            let r = Vec3::from_array(*p).length();
            assert!(
                (r - (1.0 + lift)).abs() < 0.02,
                "vertex radius {r} far from expected ~{}",
                1.0 + lift
            );
        }
    }

    #[test]
    fn patch_disc_on_sphere_side_orients_outward() {
        // Anchor on the +X face of the sphere — the patch should sit on
        // the side, not at the top. Verifies the frame uses the surface
        // normal, not a fixed world-space orientation.
        let sphere = sphere_mesh(1.0, 32, 48, UvMode::default());
        let surface = SurfaceIndex::build(&sphere);
        let disc = crate::primitives::disc_mesh(0.1, 24, UvMode::default());
        let params = PatchParams {
            up: Axis::Y,
            anchor: Vec3::new(1.0, 0.0, 0.0),
            anchor_dir: None,
            roll_ref: None,
            lift: 0.005,
        };
        let out = conform_patch(&disc, &surface, &params);
        // Every vertex lies on/near the sphere surface, and the average
        // x is ~+1 (we're on the +X face, not the top).
        let mean_x: f32 =
            out.positions.iter().map(|p| p[0]).sum::<f32>() / out.positions.len() as f32;
        assert!(
            mean_x > 0.95,
            "patch should sit on +X face, mean_x={mean_x}",
        );
        for p in &out.positions {
            let r = Vec3::from_array(*p).length();
            assert!(
                (r - 1.005).abs() < 0.02,
                "vertex {p:?} not on sphere (r={r})",
            );
        }
    }

    #[test]
    fn patch_thin_box_lays_flat_on_curved_surface() {
        // A thin box (height << footprint) used as a patch should bend
        // around a sphere, with all vertices near the sphere radius. This
        // is the case the user hits with `cylinder height=0.01` pockets.
        let sphere = sphere_mesh(1.0, 32, 48, UvMode::default());
        let surface = SurfaceIndex::build(&sphere);
        // Box 20cm × 1cm × 20cm, up axis = Y (the thin axis).
        let raw = crate::primitives::box_mesh([0.2, 0.01, 0.2], UvMode::default());
        let dense = subdivide_along_axis(&raw, Axis::X, 12);
        let dense = subdivide_along_axis(&dense, Axis::Z, 12);
        let params = PatchParams {
            up: Axis::Y,
            anchor: Vec3::new(0.0, 1.0, 0.0),
            anchor_dir: None,
            roll_ref: None,
            lift: 0.002,
        };
        let out = conform_patch(&dense, &surface, &params);
        for p in &out.positions {
            let r = Vec3::from_array(*p).length();
            // Box thickness 1cm + lift 2mm + sphere radius 1m; vertex
            // radius range is [1.002, 1.012].
            assert!(
                r > 0.99 && r < 1.03,
                "thin-box patch vertex {p:?} far from sphere (r={r})",
            );
        }
    }

    #[test]
    fn patch_empty_surface_returns_input_unchanged() {
        let empty = Mesh::default();
        let surface = SurfaceIndex::build(&empty);
        let disc = crate::primitives::disc_mesh(0.1, 12, UvMode::default());
        let params = PatchParams {
            up: Axis::Y,
            anchor: Vec3::ZERO,
            anchor_dir: None,
            roll_ref: None,
            lift: 0.0,
        };
        let out = conform_patch(&disc, &surface, &params);
        assert_eq!(out.positions, disc.positions);
    }

    #[test]
    fn patch_anchor_dir_overrides_surface_normal() {
        // Even on a flat plane, providing a custom anchor_dir flips the
        // patch's outward direction — vertices end up on the negative-Y
        // side of the plane instead of +Y.
        let plane = plane_mesh([4.0, 4.0], UvMode::default());
        let surface = SurfaceIndex::build(&plane);
        let disc = crate::primitives::disc_mesh(0.2, 16, UvMode::default());
        let params = PatchParams {
            up: Axis::Y,
            anchor: Vec3::ZERO,
            anchor_dir: Some(Vec3::new(0.0, -1.0, 0.0)),
            roll_ref: None,
            lift: 0.05,
        };
        // anchor_dir only sets the orienting frame; per-vertex height uses
        // the *surface* normal at the snapped point. So the disc still sits
        // at +y (plane faces +Y), but its in-plane axes flip — verify the
        // frame change by checking that t0/b0 still produce a planar disc.
        let out = conform_patch(&disc, &surface, &params);
        for p in &out.positions {
            assert!((p[1] - 0.05).abs() < 1e-3, "vertex y {} not at lift", p[1]);
        }
    }
}
