use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let humanoid_dir = manifest.join("src/primitives/humanoid");
    println!("cargo:rerun-if-changed=src/primitives/humanoid");

    let mut entries: Vec<String> = fs::read_dir(&humanoid_dir)
        .expect("read humanoid asset dir")
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".glb"))
        .collect();
    entries.sort();

    // One `(stdlib_key, &[u8])` row per .glb. Key is the path under
    // `humanoid/` so callers write `src="stdlib:humanoid/<file>.glb"`.
    let mut body = String::new();
    body.push_str("// generated by build.rs — do not edit by hand\n");
    body.push_str(
        "pub static HUMANOID_ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for name in &entries {
        // include_bytes! resolves relative to *this* file (the generated one),
        // which lands under OUT_DIR. Use an absolute path so it doesn't matter
        // where the include lives.
        let abs = humanoid_dir.join(name);
        body.push_str(&format!(
            "    (\"humanoid/{name}\", include_bytes!({abs:?})),\n",
            name = name,
            abs = Path::new(&abs)
        ));
    }
    body.push_str("];\n");

    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("humanoid_assets.rs");
    fs::write(&out, body).expect("write humanoid_assets.rs");
}
