[package]
name = "mgen-dsl"
version.workspace = true
edition.workspace = true

[dependencies]
mgen-core = { workspace = true }
mgen-geom = { workspace = true }
mgen-anim = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
glam = { workspace = true }
